version: "3.2"
services:
  backend:
      build: 
        context: .
        dockerfile: Dockerfile
      ports:
        - 8008:8008

networks:
    default:
        external:
            name: terra_network