version: "3.2"
services:
  backend:
      build: 
        context: .
        dockerfile: Dockerfile
      # command: 'python manage.py runserver 0.0.0.0:8008'
      container_name: dataretrieval
      ports:
        - 8000:8000
        - 5673:5672
      volumes:
        - .:/app
      environment:
        # ENVIRONMET_VARIABLE_NAME: "environment variable value" 
        API_KEY: "693518538948276"
        API_SECRET: "I_V74DpPwtkwj1yQk-Ib5aAPQyQ"        

networks:
    default:
        external:
            name: terra_network

# Docker commands to start the rabbitmq server in the same network
# docker network create terra_network
# docker run -d --network terra_network --hostname rabbitmqhost \
#  --name rabbitmq -p 15672:15672 -p 5672:5672 rabbitmq:3-management