name: for_plotting
channels:
  - conda-forge
dependencies:
  - python=3.8
  - Django==3.1.3
  - djangorestframework==3.12.2
  - mysqlclient==2.0.1
  # - django-mysql
  - django-cors-headers
  - metpy
  - boto3
  - botocore
  - matplotlib
  # - nexradaws
  - pika == 1.2.0
  - numpy
  - netCDF4