- hosts: 'terraclu-k8s-node-1 '
  become: yes
  gather_facts: yes

  tasks:
   - name: change docker driver     
     shell: |
          cat <<EOF | sudo tee /etc/docker/daemon.json
            {"exec-opts": ["native.cgroupdriver=systemd"],"log-driver": "json-file","log-opts": {"max-size": "100m"},"storage-driver": "overlay2"} EOF
    
   - name: update and reset the changes
     shell: |
            sudo systemctl daemon-reload
            sudo systemctl restart docker
            sudo kubeadm reset -f                    

   - name: Copy join command from Ansiblehost to the worker nodes.
     become: yes
     copy:
       src: /tmp/kubernetes_join_command
       dest: /tmp/kubernetes_join_command
       mode: 0777

   - name: Join the Worker nodes to the cluster.
     become: yes
     command: sh /tmp/kubernetes_join_command
     register: joined_or_not