version : '3'
services :
  sql-standalone :
    # will build SQL-STANDALONE docker container
    build : 
        context : .
        dockerfile : ./DB_docker/Dockerfile
    environment :
         MYSQL_ROOT_PASSWORD : Team_terra125
    container_name: sql-standalone
    
  service-sql:
    # will build ./docker/db/Dockerfile ==services docker
    build : 
        context : .
        dockerfile : ./Dockerfile
    command:  ["./wait-for-it.sh", "sql-standalone:3306","--strict" , "--timeout=300", "java", "-jar", "team-terra.jar"]
    ports:
        - '8888:8888'

    depends_on :
        - sql-standalone
    container_name: service-sql
        
#networks :
#    default : 
#        external :
#           name : sql_spring_network
networks:
    default:
        external:
            name: terra_network        