apiVersion: apps/v1
kind: Deployment
metadata: 
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec: 
      containers: 
      - name: gateway
        image: gauti091/api-gateway:linux
        ports:
        - containerPort: 8008
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  type: LoadBalancer
  ports:
   - protocol: TCP
     port: 8008
     targetPort: 8008
     nodePort: 30021


  
