apiVersion: apps/v1
kind: Deployment
metadata: 
  name: dataretrieval
  labels:
    app: dataretrieval
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: dataretrieval
  template:
    metadata:
      labels:
        app: dataretrieval
    spec: 
      containers: 
      - name: dataretrieval
        image: gauti091/data-retrieval:linux
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
         limits:
           memory: "300Mi"
         requests:
           memory: "300Mi"
        env:
        - name: api_key
          valueFrom:
            configMapKeyRef:
              name: secrets
              key: api_key         
        - name: api_secret
          valueFrom:
            configMapKeyRef:
              name: secrets
              key: api_secret            
---
apiVersion: v1
kind: Service
metadata:
  name: dataretrieval
spec:
  selector:
    app: dataretrieval
  type: LoadBalancer
  ports:
   - protocol: TCP
     port: 8000
     targetPort: 8000
     nodePort: 30005


  
