apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dr-scale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dataretrieval
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 10
# status:
#   observedGeneration: 1  
#   currentReplicas: 1
#   desiredReplicas: 1
#   currentMetrics:
#   - type: Resource
#     resource:
#       name: memory
#       current:
#         averageUtilization: 0
#         averageValue: 0