apiVersion: apps/v1
kind: Deployment
metadata: 
  name: userinterface
  labels:
    app: userinterface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userinterface
  template:
    metadata:
      labels:
        app: userinterface
    spec: 
      containers: 
      - name: userinterface
        image: gauti091/ui:linux
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: userinterface
  annotations:
  service.beta.kubernetes.io/openstack-internal-load-balancer: "false"
  loadbalancer.openstack.org/floating-network-id: "3fe22c05-6206-4db2-9a13-44f04b6796e6"
spec:
  selector:
    app: userinterface
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30422


  
