apiVersion: apps/v1
kind: Deployment
metadata: 
  name: service-sql
  labels:
    app: service-sql
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: service-sql
  template: 
    metadata:
      labels:
        app: service-sql
    spec: 
      containers: 
      - name: service-sql
        image: gauti091/user-management
        ports: 
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata: 
  name: service-sql
spec: 
  selector: 
    app: service-sql
  type: LoadBalancer
  ports: 
  - protocol: TCP
    port: 8888
    targetPort: 8888
    nodePort: 30123

