name: Django CI

on:
  push:
    branches: [ api-gateway ]
  pull_request:
    branches: [ api-gateway ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r data-retrieval-plotting-service/requirements.txt
    - name: Run Tests
      run: |
        cd data-retrieval-plotting-service/
        python manage.py test
